export const TYPE_CHANGE_DEBUG_MODE = 'TYPE_CHANGE_DEBUG_MODE';
export const TYPE_CHANGE_BALANCE = 'TYPE_CHANGE_BALANCE';
export const TYPE_SET_RUNNING = 'TYPE_SET_RUNNING';
export const TYPE_REPOSITION_REEL = 'TYPE_REPOSITION_REEL';
export const TYPE_CALCULATE_WINS = 'TYPE_CALCULATE_WINS';
export const TYPE_RESET_WINS = 'TYPE_RESET_WINS';
export const TYPE_SET_DEBUG_COLUMN = 'TYPE_SET_DEBUG_COLUMN';
